
#import = [
#  "~/.config/alacritty/catppuccin-mocha.toml"
#]

live_config_reload = true

[env]
TERM = "xterm-256color"



[window]
padding = { x = 10, y = 10 }
decorations = "full"
opacity = 0.7
blur = true
option_as_alt = "Both"

[font]
size = 14

[font.normal]
family = "MesloLGL Nerd Font"
style = "Regular"

[font.bold]
family = "MesloLGl Nerd Font"
style = "Bold"

[font.italic]
family = "MesloLGL Nerd Font"
style = "Italic"

[font.bold_italic]
family = "MesloLGL Nerd Font"
style = "Bold Italic"

[colors]
# Add your preferred color scheme here
[keyboard]
# Add any custom key bindings here
